### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by chmoore889** [AbdullahNauman/Breakout#1]
- [x] Make classes for basic objects
- [ ] Make menu interface @AbdullahNauman 
- [ ] Make full-screen ability
- [ ] **Add more conditions for block bouncing** @AbdullahNauman
- [x] **Fix behavior when ball hits side of paddle**(not perfect yet)
- [x] **Add space bar key listener so at beginning of levels the ball is released**
- [x] Add scoring
- [x] Add fancy border coloring
- [ ] Add my face to blocks
- [x] **Add header comments to every class**
- [x] Ask Smit about ball breaking two blocks at once then reversing direction twice
- [x] Add end game screen that that displays score
- [x] Add 'press space bar to play again'
- [ ] Shorten some long comments
- [ ] **Add shrinking paddle and block reset mechanic** @AbdullahNauman that includes a level counter that can extend the scoring or just be a scoring object

**Comment by rndev2017** [comment]
damn u guys have a lot to do

**Comment by rndev2017** [comment]
Breakout.java does not work on my computer. It keeps going to game over screen. UI looks great tho.
(fixed)

**Comment by chmoore889** [comment]
> Breakout.java does not work on my computer. It keeps going to game over screen. UI looks great tho.

Works now

**Comment by rndev2017** [comment]
Thank you chris 

always <3 you
